# numpy

In [1]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
num = np.array([1,2,3,5,6,7,8,9,0,4])
print(num)


[1 2 3 5 6 7 8 9 0 4]


In [6]:
matrix = np.array([[1,2,3,4],
                  [10,3,55,9]])
print(matrix)

[[ 1  2  3  4]
 [10  3 55  9]]


In [12]:
arr_2d = np.array([[1,2,3,],
                   [4,5,6],
                   [7,8,9]])
print(arr_2d,type(arr_2d))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [4]:
temp = [10,11.2,88,210,183,30,24,47]
average = np.mean([temp])
print(average)

75.4


In [22]:
import numpy as np

np_city = np.array([[1.64, 71.78],[1.37, 63.35], [1.76, 55.09],[2.04, 74.85],[2.04, 68.72],[2.01, 73.57],
                   [2.64, 73.78],[3.37, 65.35], [4.76, 65.09],[5.04, 76.85],[6.04, 68.72],[7.01, 73.67],
                   [1.64, 71.78],[1.37, 63.35], [1.76, 55.09],[2.04, 74.85],[2.04, 68.72],[2.01, 73.57]])

average = np.mean(np_city)
print(average)
print(np_city.size)

35.79888888888889
36


In [17]:
import numpy as np 
filled_array = np.full((3,3),1)
print(filled_array)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
arr = np.arange(1,10,2)
print(arr.astype(str))

['1' '3' '5' '7' '9']


In [21]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
import numpy as np
arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_3d = np.array([[[1,2],[3,4],[5,6]]])
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


In [41]:
arr = np.array([1,2,3,4,5])
print(arr + 5)

[ 6  7  8  9 10]


In [43]:
arr_max = np.argmax([1,2,3,4,5])
arr_max

np.int64(4)

#### TASK:
- use np.where() to filter tyhe data form weight or height array
- Given a 2D NumPy array, write a function to set the elements on the main diagonal to zero without affecting other elements.
- Given a 1D NumPy array, write a function to return the indices of the top-k largest elements.

In [12]:
weight_np = np.array([40.5,77,49.1,64,55.8])
height_np = np.array([5,5.7,4.9,6.4,5.8])

In [ ]:
np.where()